// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {
    #[derive(Debug, Clone, PartialEq)]
    pub struct IsWhitelist {
        pub param0: Vec<u8>,
    }
    impl IsWhitelist {
        const METHOD_ID: [u8; 4] = [198u8, 131u8, 99u8, 13u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                param0: substreams_ethereum::abi::read_address(data, 0, "param0")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 32usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 32usize);
            substreams_ethereum::abi::write_address_at(&mut out, base + 0, &self.param0);
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<bool, String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<bool, String> {
            Ok(substreams_ethereum::abi::read_bool(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<bool> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for IsWhitelist {
        const NAME: &'static str = "isWhitelist";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<bool> for IsWhitelist {
        fn output(data: &[u8]) -> Result<bool, String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Owner {}
    impl Owner {
        const METHOD_ID: [u8; 4] = [141u8, 165u8, 203u8, 91u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Ok(Self {})
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 0usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 0usize);
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Vec<u8>, String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Ok(substreams_ethereum::abi::read_address(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<Vec<u8>> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for Owner {
        const NAME: &'static str = "owner";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<Vec<u8>> for Owner {
        fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct RenounceOwnership {}
    impl RenounceOwnership {
        const METHOD_ID: [u8; 4] = [113u8, 80u8, 24u8, 166u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Ok(Self {})
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 0usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 0usize);
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for RenounceOwnership {
        const NAME: &'static str = "renounceOwnership";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct RescueFunds {
        pub token: Vec<u8>,
        pub amount: substreams::scalar::BigInt,
    }
    impl RescueFunds {
        const METHOD_ID: [u8; 4] = [120u8, 227u8, 33u8, 79u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                token: substreams_ethereum::abi::read_address(data, 0, "token")?,
                amount: substreams_ethereum::abi::read_uint(data, 32, "amount")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 64usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 64usize);
            substreams_ethereum::abi::write_address_at(&mut out, base + 0, &self.token);
            substreams_ethereum::abi::write_uint_at(&mut out, base + 32, &self.amount);
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for RescueFunds {
        const NAME: &'static str = "rescueFunds";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Swap {
        pub execution: (
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            (
                Vec<u8>,
                Vec<u8>,
                Vec<Vec<u8>>,
                Vec<substreams::scalar::BigInt>,
                Vec<Vec<u8>>,
                Vec<substreams::scalar::BigInt>,
                Vec<u8>,
                substreams::scalar::BigInt,
                substreams::scalar::BigInt,
                substreams::scalar::BigInt,
                Vec<u8>,
            ),
            Vec<u8>,
        ),
    }
    impl Swap {
        const METHOD_ID: [u8; 4] = [226u8, 31u8, 208u8, 233u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                execution: {
                    let base = substreams_ethereum::abi::read_dynamic_tail(
                        data,
                        0,
                        "execution",
                    )?;
                    (
                        substreams_ethereum::abi::read_address(base, 0, "execution")?,
                        substreams_ethereum::abi::read_address(base, 32, "execution")?,
                        substreams_ethereum::abi::read_bytes(base, 64, "execution")?,
                        {
                            let base = substreams_ethereum::abi::read_dynamic_tail(
                                base,
                                96,
                                "execution",
                            )?;
                            (
                                substreams_ethereum::abi::read_address(
                                    base,
                                    0,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_address(
                                    base,
                                    32,
                                    "execution",
                                )?,
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        64,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_address(
                                                tail,
                                                at,
                                                "execution",
                                            )?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        96,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_uint(tail, at, "execution")?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        128,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_address(
                                                tail,
                                                at,
                                                "execution",
                                            )?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        160,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_uint(tail, at, "execution")?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                substreams_ethereum::abi::read_address(
                                    base,
                                    192,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_uint(
                                    base,
                                    224,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_uint(
                                    base,
                                    256,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_uint(
                                    base,
                                    288,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_bytes(
                                    base,
                                    320,
                                    "execution",
                                )?,
                            )
                        },
                        substreams_ethereum::abi::read_bytes(base, 128, "execution")?,
                    )
                },
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 32usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 32usize);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        160usize,
                    );
                    substreams_ethereum::abi::write_address_at(
                        &mut out,
                        base_0 + 0,
                        &self.execution.0,
                    );
                    substreams_ethereum::abi::write_address_at(
                        &mut out,
                        base_0 + 32,
                        &self.execution.1,
                    );
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        substreams_ethereum::abi::write_bytes_tail(
                            &mut out,
                            &self.execution.2,
                        );
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 64,
                            at,
                        );
                    };
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        {
                            let base_1 = substreams_ethereum::abi::reserve_head(
                                &mut out,
                                352usize,
                            );
                            substreams_ethereum::abi::write_address_at(
                                &mut out,
                                base_1 + 0,
                                &self.execution.3.0,
                            );
                            substreams_ethereum::abi::write_address_at(
                                &mut out,
                                base_1 + 32,
                                &self.execution.3.1,
                            );
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.2.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .2
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_address_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 64,
                                    at,
                                );
                            };
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.3.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .3
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_uint_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 96,
                                    at,
                                );
                            };
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.4.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .4
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_address_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 128,
                                    at,
                                );
                            };
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.5.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .5
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_uint_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 160,
                                    at,
                                );
                            };
                            substreams_ethereum::abi::write_address_at(
                                &mut out,
                                base_1 + 192,
                                &self.execution.3.6,
                            );
                            substreams_ethereum::abi::write_uint_at(
                                &mut out,
                                base_1 + 224,
                                &self.execution.3.7,
                            );
                            substreams_ethereum::abi::write_uint_at(
                                &mut out,
                                base_1 + 256,
                                &self.execution.3.8,
                            );
                            substreams_ethereum::abi::write_uint_at(
                                &mut out,
                                base_1 + 288,
                                &self.execution.3.9,
                            );
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                substreams_ethereum::abi::write_bytes_tail(
                                    &mut out,
                                    &self.execution.3.10,
                                );
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 320,
                                    at,
                                );
                            };
                        };
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 96,
                            at,
                        );
                    };
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        substreams_ethereum::abi::write_bytes_tail(
                            &mut out,
                            &self.execution.4,
                        );
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 128,
                            at,
                        );
                    };
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 0, at);
            };
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(
            data: &[u8],
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Ok((
                substreams_ethereum::abi::read_uint(data, 0, "output")?,
                substreams_ethereum::abi::read_uint(data, 32, "output")?,
            ))
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(
            &self,
            address: Vec<u8>,
        ) -> Option<(substreams::scalar::BigInt, substreams::scalar::BigInt)> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for Swap {
        const NAME: &'static str = "swap";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<
        (substreams::scalar::BigInt, substreams::scalar::BigInt),
    > for Swap {
        fn output(
            data: &[u8],
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct SwapGeneric {
        pub execution: (
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            (
                Vec<u8>,
                Vec<u8>,
                Vec<Vec<u8>>,
                Vec<substreams::scalar::BigInt>,
                Vec<Vec<u8>>,
                Vec<substreams::scalar::BigInt>,
                Vec<u8>,
                substreams::scalar::BigInt,
                substreams::scalar::BigInt,
                substreams::scalar::BigInt,
                Vec<u8>,
            ),
            Vec<u8>,
        ),
    }
    impl SwapGeneric {
        const METHOD_ID: [u8; 4] = [89u8, 229u8, 15u8, 237u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                execution: {
                    let base = substreams_ethereum::abi::read_dynamic_tail(
                        data,
                        0,
                        "execution",
                    )?;
                    (
                        substreams_ethereum::abi::read_address(base, 0, "execution")?,
                        substreams_ethereum::abi::read_address(base, 32, "execution")?,
                        substreams_ethereum::abi::read_bytes(base, 64, "execution")?,
                        {
                            let base = substreams_ethereum::abi::read_dynamic_tail(
                                base,
                                96,
                                "execution",
                            )?;
                            (
                                substreams_ethereum::abi::read_address(
                                    base,
                                    0,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_address(
                                    base,
                                    32,
                                    "execution",
                                )?,
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        64,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_address(
                                                tail,
                                                at,
                                                "execution",
                                            )?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        96,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_uint(tail, at, "execution")?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        128,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_address(
                                                tail,
                                                at,
                                                "execution",
                                            )?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                {
                                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                        base,
                                        160,
                                        "execution",
                                    )?;
                                    let mut out = Vec::with_capacity(count.min(1024));
                                    let mut at = 0usize;
                                    for _ in 0..count {
                                        out.push(
                                            substreams_ethereum::abi::read_uint(tail, at, "execution")?,
                                        );
                                        at += 32usize;
                                    }
                                    out
                                },
                                substreams_ethereum::abi::read_address(
                                    base,
                                    192,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_uint(
                                    base,
                                    224,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_uint(
                                    base,
                                    256,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_uint(
                                    base,
                                    288,
                                    "execution",
                                )?,
                                substreams_ethereum::abi::read_bytes(
                                    base,
                                    320,
                                    "execution",
                                )?,
                            )
                        },
                        substreams_ethereum::abi::read_bytes(base, 128, "execution")?,
                    )
                },
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 32usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 32usize);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        160usize,
                    );
                    substreams_ethereum::abi::write_address_at(
                        &mut out,
                        base_0 + 0,
                        &self.execution.0,
                    );
                    substreams_ethereum::abi::write_address_at(
                        &mut out,
                        base_0 + 32,
                        &self.execution.1,
                    );
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        substreams_ethereum::abi::write_bytes_tail(
                            &mut out,
                            &self.execution.2,
                        );
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 64,
                            at,
                        );
                    };
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        {
                            let base_1 = substreams_ethereum::abi::reserve_head(
                                &mut out,
                                352usize,
                            );
                            substreams_ethereum::abi::write_address_at(
                                &mut out,
                                base_1 + 0,
                                &self.execution.3.0,
                            );
                            substreams_ethereum::abi::write_address_at(
                                &mut out,
                                base_1 + 32,
                                &self.execution.3.1,
                            );
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.2.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .2
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_address_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 64,
                                    at,
                                );
                            };
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.3.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .3
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_uint_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 96,
                                    at,
                                );
                            };
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.4.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .4
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_address_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 128,
                                    at,
                                );
                            };
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                {
                                    let count = self.execution.3.5.len();
                                    substreams_ethereum::abi::write_offset(&mut out, count);
                                    let base_2 = substreams_ethereum::abi::reserve_head(
                                        &mut out,
                                        count * 32usize,
                                    );
                                    for (index, element_2) in self
                                        .execution
                                        .3
                                        .5
                                        .iter()
                                        .enumerate()
                                    {
                                        let slot = index * 32usize;
                                        substreams_ethereum::abi::write_uint_at(
                                            &mut out,
                                            base_2 + slot,
                                            &element_2,
                                        );
                                    }
                                };
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 160,
                                    at,
                                );
                            };
                            substreams_ethereum::abi::write_address_at(
                                &mut out,
                                base_1 + 192,
                                &self.execution.3.6,
                            );
                            substreams_ethereum::abi::write_uint_at(
                                &mut out,
                                base_1 + 224,
                                &self.execution.3.7,
                            );
                            substreams_ethereum::abi::write_uint_at(
                                &mut out,
                                base_1 + 256,
                                &self.execution.3.8,
                            );
                            substreams_ethereum::abi::write_uint_at(
                                &mut out,
                                base_1 + 288,
                                &self.execution.3.9,
                            );
                            {
                                let at = substreams_ethereum::abi::tail_offset(
                                    &out,
                                    base_1,
                                );
                                substreams_ethereum::abi::write_bytes_tail(
                                    &mut out,
                                    &self.execution.3.10,
                                );
                                substreams_ethereum::abi::backfill_offset(
                                    &mut out,
                                    base_1 + 320,
                                    at,
                                );
                            };
                        };
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 96,
                            at,
                        );
                    };
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        substreams_ethereum::abi::write_bytes_tail(
                            &mut out,
                            &self.execution.4,
                        );
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 128,
                            at,
                        );
                    };
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 0, at);
            };
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(
            data: &[u8],
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Ok((
                substreams_ethereum::abi::read_uint(data, 0, "output")?,
                substreams_ethereum::abi::read_uint(data, 32, "output")?,
            ))
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(
            &self,
            address: Vec<u8>,
        ) -> Option<(substreams::scalar::BigInt, substreams::scalar::BigInt)> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for SwapGeneric {
        const NAME: &'static str = "swapGeneric";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<
        (substreams::scalar::BigInt, substreams::scalar::BigInt),
    > for SwapGeneric {
        fn output(
            data: &[u8],
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct SwapSimpleMode {
        pub caller: Vec<u8>,
        pub desc: (
            Vec<u8>,
            Vec<u8>,
            Vec<Vec<u8>>,
            Vec<substreams::scalar::BigInt>,
            Vec<Vec<u8>>,
            Vec<substreams::scalar::BigInt>,
            Vec<u8>,
            substreams::scalar::BigInt,
            substreams::scalar::BigInt,
            substreams::scalar::BigInt,
            Vec<u8>,
        ),
        pub executor_data: Vec<u8>,
        pub client_data: Vec<u8>,
    }
    impl SwapSimpleMode {
        const METHOD_ID: [u8; 4] = [138u8, 240u8, 51u8, 251u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                caller: substreams_ethereum::abi::read_address(data, 0, "caller")?,
                desc: {
                    let base = substreams_ethereum::abi::read_dynamic_tail(
                        data,
                        32,
                        "desc",
                    )?;
                    (
                        substreams_ethereum::abi::read_address(base, 0, "desc")?,
                        substreams_ethereum::abi::read_address(base, 32, "desc")?,
                        {
                            let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                base,
                                64,
                                "desc",
                            )?;
                            let mut out = Vec::with_capacity(count.min(1024));
                            let mut at = 0usize;
                            for _ in 0..count {
                                out.push(
                                    substreams_ethereum::abi::read_address(tail, at, "desc")?,
                                );
                                at += 32usize;
                            }
                            out
                        },
                        {
                            let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                base,
                                96,
                                "desc",
                            )?;
                            let mut out = Vec::with_capacity(count.min(1024));
                            let mut at = 0usize;
                            for _ in 0..count {
                                out.push(
                                    substreams_ethereum::abi::read_uint(tail, at, "desc")?,
                                );
                                at += 32usize;
                            }
                            out
                        },
                        {
                            let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                base,
                                128,
                                "desc",
                            )?;
                            let mut out = Vec::with_capacity(count.min(1024));
                            let mut at = 0usize;
                            for _ in 0..count {
                                out.push(
                                    substreams_ethereum::abi::read_address(tail, at, "desc")?,
                                );
                                at += 32usize;
                            }
                            out
                        },
                        {
                            let (tail, count) = substreams_ethereum::abi::read_array_tail(
                                base,
                                160,
                                "desc",
                            )?;
                            let mut out = Vec::with_capacity(count.min(1024));
                            let mut at = 0usize;
                            for _ in 0..count {
                                out.push(
                                    substreams_ethereum::abi::read_uint(tail, at, "desc")?,
                                );
                                at += 32usize;
                            }
                            out
                        },
                        substreams_ethereum::abi::read_address(base, 192, "desc")?,
                        substreams_ethereum::abi::read_uint(base, 224, "desc")?,
                        substreams_ethereum::abi::read_uint(base, 256, "desc")?,
                        substreams_ethereum::abi::read_uint(base, 288, "desc")?,
                        substreams_ethereum::abi::read_bytes(base, 320, "desc")?,
                    )
                },
                executor_data: substreams_ethereum::abi::read_bytes(
                    data,
                    64,
                    "executor_data",
                )?,
                client_data: substreams_ethereum::abi::read_bytes(
                    data,
                    96,
                    "client_data",
                )?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 128usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 128usize);
            substreams_ethereum::abi::write_address_at(&mut out, base + 0, &self.caller);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        352usize,
                    );
                    substreams_ethereum::abi::write_address_at(
                        &mut out,
                        base_0 + 0,
                        &self.desc.0,
                    );
                    substreams_ethereum::abi::write_address_at(
                        &mut out,
                        base_0 + 32,
                        &self.desc.1,
                    );
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        {
                            let count = self.desc.2.len();
                            substreams_ethereum::abi::write_offset(&mut out, count);
                            let base_1 = substreams_ethereum::abi::reserve_head(
                                &mut out,
                                count * 32usize,
                            );
                            for (index, element_1) in self.desc.2.iter().enumerate() {
                                let slot = index * 32usize;
                                substreams_ethereum::abi::write_address_at(
                                    &mut out,
                                    base_1 + slot,
                                    &element_1,
                                );
                            }
                        };
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 64,
                            at,
                        );
                    };
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        {
                            let count = self.desc.3.len();
                            substreams_ethereum::abi::write_offset(&mut out, count);
                            let base_1 = substreams_ethereum::abi::reserve_head(
                                &mut out,
                                count * 32usize,
                            );
                            for (index, element_1) in self.desc.3.iter().enumerate() {
                                let slot = index * 32usize;
                                substreams_ethereum::abi::write_uint_at(
                                    &mut out,
                                    base_1 + slot,
                                    &element_1,
                                );
                            }
                        };
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 96,
                            at,
                        );
                    };
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        {
                            let count = self.desc.4.len();
                            substreams_ethereum::abi::write_offset(&mut out, count);
                            let base_1 = substreams_ethereum::abi::reserve_head(
                                &mut out,
                                count * 32usize,
                            );
                            for (index, element_1) in self.desc.4.iter().enumerate() {
                                let slot = index * 32usize;
                                substreams_ethereum::abi::write_address_at(
                                    &mut out,
                                    base_1 + slot,
                                    &element_1,
                                );
                            }
                        };
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 128,
                            at,
                        );
                    };
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        {
                            let count = self.desc.5.len();
                            substreams_ethereum::abi::write_offset(&mut out, count);
                            let base_1 = substreams_ethereum::abi::reserve_head(
                                &mut out,
                                count * 32usize,
                            );
                            for (index, element_1) in self.desc.5.iter().enumerate() {
                                let slot = index * 32usize;
                                substreams_ethereum::abi::write_uint_at(
                                    &mut out,
                                    base_1 + slot,
                                    &element_1,
                                );
                            }
                        };
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 160,
                            at,
                        );
                    };
                    substreams_ethereum::abi::write_address_at(
                        &mut out,
                        base_0 + 192,
                        &self.desc.6,
                    );
                    substreams_ethereum::abi::write_uint_at(
                        &mut out,
                        base_0 + 224,
                        &self.desc.7,
                    );
                    substreams_ethereum::abi::write_uint_at(
                        &mut out,
                        base_0 + 256,
                        &self.desc.8,
                    );
                    substreams_ethereum::abi::write_uint_at(
                        &mut out,
                        base_0 + 288,
                        &self.desc.9,
                    );
                    {
                        let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                        substreams_ethereum::abi::write_bytes_tail(
                            &mut out,
                            &self.desc.10,
                        );
                        substreams_ethereum::abi::backfill_offset(
                            &mut out,
                            base_0 + 320,
                            at,
                        );
                    };
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 32, at);
            };
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(
                    &mut out,
                    &self.executor_data,
                );
                substreams_ethereum::abi::backfill_offset(&mut out, base + 64, at);
            };
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(&mut out, &self.client_data);
                substreams_ethereum::abi::backfill_offset(&mut out, base + 96, at);
            };
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(
            data: &[u8],
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Ok((
                substreams_ethereum::abi::read_uint(data, 0, "output")?,
                substreams_ethereum::abi::read_uint(data, 32, "output")?,
            ))
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(
            &self,
            address: Vec<u8>,
        ) -> Option<(substreams::scalar::BigInt, substreams::scalar::BigInt)> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for SwapSimpleMode {
        const NAME: &'static str = "swapSimpleMode";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<
        (substreams::scalar::BigInt, substreams::scalar::BigInt),
    > for SwapSimpleMode {
        fn output(
            data: &[u8],
        ) -> Result<(substreams::scalar::BigInt, substreams::scalar::BigInt), String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct TransferOwnership {
        pub new_owner: Vec<u8>,
    }
    impl TransferOwnership {
        const METHOD_ID: [u8; 4] = [242u8, 253u8, 227u8, 139u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                new_owner: substreams_ethereum::abi::read_address(data, 0, "new_owner")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 32usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 32usize);
            substreams_ethereum::abi::write_address_at(
                &mut out,
                base + 0,
                &self.new_owner,
            );
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for TransferOwnership {
        const NAME: &'static str = "transferOwnership";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct UpdateWhitelist {
        pub addr: Vec<Vec<u8>>,
        pub value: Vec<bool>,
    }
    impl UpdateWhitelist {
        const METHOD_ID: [u8; 4] = [51u8, 50u8, 13u8, 227u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                addr: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        data,
                        0,
                        "addr",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_address(tail, at, "addr")?,
                        );
                        at += 32usize;
                    }
                    out
                },
                value: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        data,
                        32,
                        "value",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_bool(tail, at, "value")?,
                        );
                        at += 32usize;
                    }
                    out
                },
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 64usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 64usize);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let count = self.addr.len();
                    substreams_ethereum::abi::write_offset(&mut out, count);
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        count * 32usize,
                    );
                    for (index, element_0) in self.addr.iter().enumerate() {
                        let slot = index * 32usize;
                        substreams_ethereum::abi::write_address_at(
                            &mut out,
                            base_0 + slot,
                            &element_0,
                        );
                    }
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 0, at);
            };
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let count = self.value.len();
                    substreams_ethereum::abi::write_offset(&mut out, count);
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        count * 32usize,
                    );
                    for (index, element_0) in self.value.iter().enumerate() {
                        let slot = index * 32usize;
                        substreams_ethereum::abi::write_bool_at(
                            &mut out,
                            base_0 + slot,
                            &element_0,
                        );
                    }
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 32, at);
            };
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for UpdateWhitelist {
        const NAME: &'static str = "updateWhitelist";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Weth {}
    impl Weth {
        const METHOD_ID: [u8; 4] = [173u8, 92u8, 70u8, 72u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Ok(Self {})
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 0usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 0usize);
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Vec<u8>, String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Ok(substreams_ethereum::abi::read_address(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<Vec<u8>> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for Weth {
        const NAME: &'static str = "WETH";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<Vec<u8>> for Weth {
        fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Self::output(data)
        }
    }
}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct ClientData {
        pub client_data: Vec<u8>,
    }
    impl ClientData {
        const TOPIC_ID: [u8; 32] = [
            9u8,
            94u8,
            102u8,
            250u8,
            77u8,
            214u8,
            166u8,
            247u8,
            180u8,
            63u8,
            184u8,
            68u8,
            74u8,
            123u8,
            208u8,
            237u8,
            184u8,
            112u8,
            80u8,
            140u8,
            122u8,
            191u8,
            99u8,
            155u8,
            194u8,
            22u8,
            239u8,
            176u8,
            188u8,
            255u8,
            151u8,
            121u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() < 64usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 64usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 64usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                client_data: substreams_ethereum::abi::read_bytes(
                    log.data(),
                    0,
                    "client_data",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for ClientData {
        const NAME: &'static str = "ClientData";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Error {
        pub reason: String,
    }
    impl Error {
        const TOPIC_ID: [u8; 32] = [
            8u8,
            195u8,
            121u8,
            160u8,
            175u8,
            204u8,
            50u8,
            177u8,
            163u8,
            147u8,
            2u8,
            247u8,
            203u8,
            128u8,
            115u8,
            53u8,
            150u8,
            152u8,
            65u8,
            26u8,
            181u8,
            253u8,
            110u8,
            62u8,
            219u8,
            44u8,
            2u8,
            192u8,
            181u8,
            251u8,
            168u8,
            170u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() < 64usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 64usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 64usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                reason: substreams_ethereum::abi::read_string(log.data(), 0, "reason")?,
            })
        }
    }
    impl substreams_ethereum::Event for Error {
        const NAME: &'static str = "Error";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Exchange {
        pub pair: Vec<u8>,
        pub amount_out: substreams::scalar::BigInt,
        pub output: Vec<u8>,
    }
    impl Exchange {
        const TOPIC_ID: [u8; 32] = [
            221u8,
            172u8,
            64u8,
            147u8,
            127u8,
            53u8,
            56u8,
            90u8,
            52u8,
            247u8,
            33u8,
            175u8,
            41u8,
            46u8,
            90u8,
            131u8,
            252u8,
            91u8,
            132u8,
            15u8,
            114u8,
            43u8,
            255u8,
            87u8,
            194u8,
            252u8,
            113u8,
            173u8,
            186u8,
            112u8,
            140u8,
            72u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() != 96usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 96usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 96usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                pair: substreams_ethereum::abi::read_address(log.data(), 0, "pair")?,
                amount_out: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "amount_out",
                )?,
                output: substreams_ethereum::abi::read_address(log.data(), 64, "output")?,
            })
        }
    }
    impl substreams_ethereum::Event for Exchange {
        const NAME: &'static str = "Exchange";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Fee {
        pub token: Vec<u8>,
        pub total_amount: substreams::scalar::BigInt,
        pub total_fee: substreams::scalar::BigInt,
        pub recipients: Vec<Vec<u8>>,
        pub amounts: Vec<substreams::scalar::BigInt>,
        pub is_bps: bool,
    }
    impl Fee {
        const TOPIC_ID: [u8; 32] = [
            76u8,
            57u8,
            183u8,
            206u8,
            95u8,
            79u8,
            81u8,
            79u8,
            69u8,
            203u8,
            111u8,
            130u8,
            177u8,
            113u8,
            184u8,
            176u8,
            183u8,
            242u8,
            203u8,
            244u8,
            136u8,
            173u8,
            40u8,
            228u8,
            239u8,
            244u8,
            81u8,
            88u8,
            142u8,
            47u8,
            1u8,
            75u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() < 256usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 256usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 256usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                token: substreams_ethereum::abi::read_address(log.data(), 0, "token")?,
                total_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "total_amount",
                )?,
                total_fee: substreams_ethereum::abi::read_uint(
                    log.data(),
                    64,
                    "total_fee",
                )?,
                recipients: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        log.data(),
                        96,
                        "recipients",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_address(
                                tail,
                                at,
                                "recipients",
                            )?,
                        );
                        at += 32usize;
                    }
                    out
                },
                amounts: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        log.data(),
                        128,
                        "amounts",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_uint(tail, at, "amounts")?,
                        );
                        at += 32usize;
                    }
                    out
                },
                is_bps: substreams_ethereum::abi::read_bool(log.data(), 160, "is_bps")?,
            })
        }
    }
    impl substreams_ethereum::Event for Fee {
        const NAME: &'static str = "Fee";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct OwnershipTransferred {
        pub previous_owner: Vec<u8>,
        pub new_owner: Vec<u8>,
    }
    impl OwnershipTransferred {
        const TOPIC_ID: [u8; 32] = [
            139u8,
            224u8,
            7u8,
            156u8,
            83u8,
            22u8,
            89u8,
            20u8,
            19u8,
            68u8,
            205u8,
            31u8,
            208u8,
            164u8,
            242u8,
            132u8,
            25u8,
            73u8,
            127u8,
            151u8,
            34u8,
            163u8,
            218u8,
            175u8,
            227u8,
            180u8,
            24u8,
            111u8,
            107u8,
            100u8,
            87u8,
            224u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 0usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            Ok(Self {
                previous_owner: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "previous_owner",
                )?,
                new_owner: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "new_owner",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for OwnershipTransferred {
        const NAME: &'static str = "OwnershipTransferred";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Swapped {
        pub sender: Vec<u8>,
        pub src_token: Vec<u8>,
        pub dst_token: Vec<u8>,
        pub dst_receiver: Vec<u8>,
        pub spent_amount: substreams::scalar::BigInt,
        pub return_amount: substreams::scalar::BigInt,
    }
    impl Swapped {
        const TOPIC_ID: [u8; 32] = [
            214u8,
            212u8,
            245u8,
            104u8,
            28u8,
            36u8,
            108u8,
            159u8,
            66u8,
            194u8,
            3u8,
            226u8,
            135u8,
            151u8,
            90u8,
            241u8,
            96u8,
            31u8,
            141u8,
            248u8,
            3u8,
            90u8,
            146u8,
            81u8,
            247u8,
            154u8,
            171u8,
            92u8,
            143u8,
            9u8,
            226u8,
            248u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() != 192usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 192usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 192usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                sender: substreams_ethereum::abi::read_address(log.data(), 0, "sender")?,
                src_token: substreams_ethereum::abi::read_address(
                    log.data(),
                    32,
                    "src_token",
                )?,
                dst_token: substreams_ethereum::abi::read_address(
                    log.data(),
                    64,
                    "dst_token",
                )?,
                dst_receiver: substreams_ethereum::abi::read_address(
                    log.data(),
                    96,
                    "dst_receiver",
                )?,
                spent_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    128,
                    "spent_amount",
                )?,
                return_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    160,
                    "return_amount",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for Swapped {
        const NAME: &'static str = "Swapped";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}

/// Contract's constructor arguments.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod constructor {
    const INTERNAL_ERR: &str = "`ethabi_derive` internal error";
    #[derive(Debug, Clone, PartialEq)]
    pub struct Constructor {
        pub weth: Vec<u8>,
    }
    impl Constructor {
        pub fn decode(data: &[u8]) -> Result<Self, String> {
            let mut values = ethabi::decode(&[ethabi::ParamType::Address], data.as_ref())
                .map_err(|e| format!("unable to decode constructor input: {:?}", e))?;
            values.reverse();
            Ok(Self {
                weth: values
                    .pop()
                    .expect(INTERNAL_ERR)
                    .into_address()
                    .expect(INTERNAL_ERR)
                    .as_bytes()
                    .to_vec(),
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            ethabi::encode(
                &[ethabi::Token::Address(ethabi::Address::from_slice(&self.weth))],
            )
        }
    }
}
