[package]
name = "substreams-abis"
version = "2.0.0"
description = "Substreams ABIs"
license = "MIT"
edition = "2021"
authors = ["Denis <denis@pinax.network>"]
repository = "https://github.com/pinax-network/substreams-abis"
documentation = "https://docs.rs/substreams-abis"
homepage = "https://github.com/pinax-network/substreams-abis"

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
ethabi = { version = "17.2.0", default-features = false }
substreams = "0.8.0"
substreams-ethereum = "0.12.0"
num-bigint = "0.4"
