// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {
    #[derive(Debug, Clone, PartialEq)]
    pub struct CollectRewards {
        pub looks_rare_claim: Vec<u8>,
    }
    impl CollectRewards {
        const METHOD_ID: [u8; 4] = [112u8, 154u8, 28u8, 194u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                looks_rare_claim: substreams_ethereum::abi::read_bytes(
                    data,
                    0,
                    "looks_rare_claim",
                )?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 32usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 32usize);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(
                    &mut out,
                    &self.looks_rare_claim,
                );
                substreams_ethereum::abi::backfill_offset(&mut out, base + 0, at);
            };
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for CollectRewards {
        const NAME: &'static str = "collectRewards";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Execute1 {
        pub commands: Vec<u8>,
        pub inputs: Vec<Vec<u8>>,
    }
    impl Execute1 {
        const METHOD_ID: [u8; 4] = [36u8, 133u8, 107u8, 195u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                commands: substreams_ethereum::abi::read_bytes(data, 0, "commands")?,
                inputs: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        data,
                        32,
                        "inputs",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_bytes(tail, at, "inputs")?,
                        );
                        at += 32usize;
                    }
                    out
                },
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 64usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 64usize);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(&mut out, &self.commands);
                substreams_ethereum::abi::backfill_offset(&mut out, base + 0, at);
            };
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let count = self.inputs.len();
                    substreams_ethereum::abi::write_offset(&mut out, count);
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        count * 32usize,
                    );
                    for (index, element_0) in self.inputs.iter().enumerate() {
                        let slot = index * 32usize;
                        {
                            let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                            substreams_ethereum::abi::write_bytes_tail(
                                &mut out,
                                &element_0,
                            );
                            substreams_ethereum::abi::backfill_offset(
                                &mut out,
                                base_0 + slot,
                                at,
                            );
                        };
                    }
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 32, at);
            };
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for Execute1 {
        const NAME: &'static str = "execute";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Execute2 {
        pub commands: Vec<u8>,
        pub inputs: Vec<Vec<u8>>,
        pub deadline: substreams::scalar::BigInt,
    }
    impl Execute2 {
        const METHOD_ID: [u8; 4] = [53u8, 147u8, 86u8, 76u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                commands: substreams_ethereum::abi::read_bytes(data, 0, "commands")?,
                inputs: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        data,
                        32,
                        "inputs",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_bytes(tail, at, "inputs")?,
                        );
                        at += 32usize;
                    }
                    out
                },
                deadline: substreams_ethereum::abi::read_uint(data, 64, "deadline")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 96usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 96usize);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(&mut out, &self.commands);
                substreams_ethereum::abi::backfill_offset(&mut out, base + 0, at);
            };
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let count = self.inputs.len();
                    substreams_ethereum::abi::write_offset(&mut out, count);
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        count * 32usize,
                    );
                    for (index, element_0) in self.inputs.iter().enumerate() {
                        let slot = index * 32usize;
                        {
                            let at = substreams_ethereum::abi::tail_offset(&out, base_0);
                            substreams_ethereum::abi::write_bytes_tail(
                                &mut out,
                                &element_0,
                            );
                            substreams_ethereum::abi::backfill_offset(
                                &mut out,
                                base_0 + slot,
                                at,
                            );
                        };
                    }
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 32, at);
            };
            substreams_ethereum::abi::write_uint_at(&mut out, base + 64, &self.deadline);
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for Execute2 {
        const NAME: &'static str = "execute";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct OnErc1155BatchReceived {
        pub param0: Vec<u8>,
        pub param1: Vec<u8>,
        pub param2: Vec<substreams::scalar::BigInt>,
        pub param3: Vec<substreams::scalar::BigInt>,
        pub param4: Vec<u8>,
    }
    impl OnErc1155BatchReceived {
        const METHOD_ID: [u8; 4] = [188u8, 25u8, 124u8, 129u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                param0: substreams_ethereum::abi::read_address(data, 0, "param0")?,
                param1: substreams_ethereum::abi::read_address(data, 32, "param1")?,
                param2: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        data,
                        64,
                        "param2",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_uint(tail, at, "param2")?,
                        );
                        at += 32usize;
                    }
                    out
                },
                param3: {
                    let (tail, count) = substreams_ethereum::abi::read_array_tail(
                        data,
                        96,
                        "param3",
                    )?;
                    let mut out = Vec::with_capacity(count.min(1024));
                    let mut at = 0usize;
                    for _ in 0..count {
                        out.push(
                            substreams_ethereum::abi::read_uint(tail, at, "param3")?,
                        );
                        at += 32usize;
                    }
                    out
                },
                param4: substreams_ethereum::abi::read_bytes(data, 128, "param4")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 160usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 160usize);
            substreams_ethereum::abi::write_address_at(&mut out, base + 0, &self.param0);
            substreams_ethereum::abi::write_address_at(
                &mut out,
                base + 32,
                &self.param1,
            );
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let count = self.param2.len();
                    substreams_ethereum::abi::write_offset(&mut out, count);
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        count * 32usize,
                    );
                    for (index, element_0) in self.param2.iter().enumerate() {
                        let slot = index * 32usize;
                        substreams_ethereum::abi::write_uint_at(
                            &mut out,
                            base_0 + slot,
                            &element_0,
                        );
                    }
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 64, at);
            };
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                {
                    let count = self.param3.len();
                    substreams_ethereum::abi::write_offset(&mut out, count);
                    let base_0 = substreams_ethereum::abi::reserve_head(
                        &mut out,
                        count * 32usize,
                    );
                    for (index, element_0) in self.param3.iter().enumerate() {
                        let slot = index * 32usize;
                        substreams_ethereum::abi::write_uint_at(
                            &mut out,
                            base_0 + slot,
                            &element_0,
                        );
                    }
                };
                substreams_ethereum::abi::backfill_offset(&mut out, base + 96, at);
            };
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(&mut out, &self.param4);
                substreams_ethereum::abi::backfill_offset(&mut out, base + 128, at);
            };
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<[u8; 4usize], String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<[u8; 4usize], String> {
            Ok(substreams_ethereum::abi::read_fixed_bytes::<4>(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<[u8; 4usize]> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for OnErc1155BatchReceived {
        const NAME: &'static str = "onERC1155BatchReceived";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<[u8; 4usize]>
    for OnErc1155BatchReceived {
        fn output(data: &[u8]) -> Result<[u8; 4usize], String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct OnErc1155Received {
        pub param0: Vec<u8>,
        pub param1: Vec<u8>,
        pub param2: substreams::scalar::BigInt,
        pub param3: substreams::scalar::BigInt,
        pub param4: Vec<u8>,
    }
    impl OnErc1155Received {
        const METHOD_ID: [u8; 4] = [242u8, 58u8, 110u8, 97u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                param0: substreams_ethereum::abi::read_address(data, 0, "param0")?,
                param1: substreams_ethereum::abi::read_address(data, 32, "param1")?,
                param2: substreams_ethereum::abi::read_uint(data, 64, "param2")?,
                param3: substreams_ethereum::abi::read_uint(data, 96, "param3")?,
                param4: substreams_ethereum::abi::read_bytes(data, 128, "param4")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 160usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 160usize);
            substreams_ethereum::abi::write_address_at(&mut out, base + 0, &self.param0);
            substreams_ethereum::abi::write_address_at(
                &mut out,
                base + 32,
                &self.param1,
            );
            substreams_ethereum::abi::write_uint_at(&mut out, base + 64, &self.param2);
            substreams_ethereum::abi::write_uint_at(&mut out, base + 96, &self.param3);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(&mut out, &self.param4);
                substreams_ethereum::abi::backfill_offset(&mut out, base + 128, at);
            };
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<[u8; 4usize], String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<[u8; 4usize], String> {
            Ok(substreams_ethereum::abi::read_fixed_bytes::<4>(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<[u8; 4usize]> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for OnErc1155Received {
        const NAME: &'static str = "onERC1155Received";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<[u8; 4usize]> for OnErc1155Received {
        fn output(data: &[u8]) -> Result<[u8; 4usize], String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct OnErc721Received {
        pub param0: Vec<u8>,
        pub param1: Vec<u8>,
        pub param2: substreams::scalar::BigInt,
        pub param3: Vec<u8>,
    }
    impl OnErc721Received {
        const METHOD_ID: [u8; 4] = [21u8, 11u8, 122u8, 2u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                param0: substreams_ethereum::abi::read_address(data, 0, "param0")?,
                param1: substreams_ethereum::abi::read_address(data, 32, "param1")?,
                param2: substreams_ethereum::abi::read_uint(data, 64, "param2")?,
                param3: substreams_ethereum::abi::read_bytes(data, 96, "param3")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 128usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 128usize);
            substreams_ethereum::abi::write_address_at(&mut out, base + 0, &self.param0);
            substreams_ethereum::abi::write_address_at(
                &mut out,
                base + 32,
                &self.param1,
            );
            substreams_ethereum::abi::write_uint_at(&mut out, base + 64, &self.param2);
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(&mut out, &self.param3);
                substreams_ethereum::abi::backfill_offset(&mut out, base + 96, at);
            };
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<[u8; 4usize], String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<[u8; 4usize], String> {
            Ok(substreams_ethereum::abi::read_fixed_bytes::<4>(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<[u8; 4usize]> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for OnErc721Received {
        const NAME: &'static str = "onERC721Received";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<[u8; 4usize]> for OnErc721Received {
        fn output(data: &[u8]) -> Result<[u8; 4usize], String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct SupportsInterface {
        pub interface_id: [u8; 4usize],
    }
    impl SupportsInterface {
        const METHOD_ID: [u8; 4] = [1u8, 255u8, 201u8, 167u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                interface_id: substreams_ethereum::abi::read_fixed_bytes::<
                    4,
                >(data, 0, "interface_id")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 32usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 32usize);
            substreams_ethereum::abi::write_fixed_bytes_at(
                &mut out,
                base + 0,
                self.interface_id.as_ref(),
            );
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<bool, String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<bool, String> {
            Ok(substreams_ethereum::abi::read_bool(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<bool> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for SupportsInterface {
        const NAME: &'static str = "supportsInterface";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<bool> for SupportsInterface {
        fn output(data: &[u8]) -> Result<bool, String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct UniswapV3SwapCallback {
        pub amount0_delta: substreams::scalar::BigInt,
        pub amount1_delta: substreams::scalar::BigInt,
        pub data: Vec<u8>,
    }
    impl UniswapV3SwapCallback {
        const METHOD_ID: [u8; 4] = [250u8, 70u8, 30u8, 51u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                amount0_delta: substreams_ethereum::abi::read_int(
                    data,
                    0,
                    "amount0_delta",
                )?,
                amount1_delta: substreams_ethereum::abi::read_int(
                    data,
                    32,
                    "amount1_delta",
                )?,
                data: substreams_ethereum::abi::read_bytes(data, 64, "data")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 96usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 96usize);
            substreams_ethereum::abi::write_int_at(
                &mut out,
                base + 0,
                &self.amount0_delta,
            );
            substreams_ethereum::abi::write_int_at(
                &mut out,
                base + 32,
                &self.amount1_delta,
            );
            {
                let at = substreams_ethereum::abi::tail_offset(&out, base);
                substreams_ethereum::abi::write_bytes_tail(&mut out, &self.data);
                substreams_ethereum::abi::backfill_offset(&mut out, base + 64, at);
            };
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for UniswapV3SwapCallback {
        const NAME: &'static str = "uniswapV3SwapCallback";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct RewardsSent {
        pub amount: substreams::scalar::BigInt,
    }
    impl RewardsSent {
        const TOPIC_ID: [u8; 32] = [
            30u8,
            143u8,
            3u8,
            247u8,
            22u8,
            188u8,
            16u8,
            75u8,
            247u8,
            215u8,
            40u8,
            19u8,
            25u8,
            103u8,
            160u8,
            199u8,
            113u8,
            232u8,
            90u8,
            181u8,
            77u8,
            9u8,
            193u8,
            226u8,
            214u8,
            237u8,
            158u8,
            11u8,
            196u8,
            226u8,
            161u8,
            108u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                amount: substreams_ethereum::abi::read_uint(log.data(), 0, "amount")?,
            })
        }
    }
    impl substreams_ethereum::Event for RewardsSent {
        const NAME: &'static str = "RewardsSent";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}

/// Contract's constructor arguments.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod constructor {
    const INTERNAL_ERR: &str = "`ethabi_derive` internal error";
    #[derive(Clone)]
    pub struct Constructor {
        pub params: (
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            Vec<u8>,
            [u8; 32usize],
            [u8; 32usize],
        ),
    }
    impl Constructor {
        pub fn decode(data: &[u8]) -> Result<Self, String> {
            let mut values = ethabi::decode(
                    &[
                        ethabi::ParamType::Tuple(
                            vec![
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::Address, ethabi::ParamType::Address,
                                ethabi::ParamType::FixedBytes(32usize),
                                ethabi::ParamType::FixedBytes(32usize)
                            ],
                        ),
                    ],
                    data.as_ref(),
                )
                .map_err(|e| format!("unable to decode constructor input: {:?}", e))?;
            values.reverse();
            Ok(Self {
                params: {
                    let tuple_elements = values
                        .pop()
                        .expect(INTERNAL_ERR)
                        .into_tuple()
                        .expect(INTERNAL_ERR);
                    (
                        tuple_elements[0usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[1usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[2usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[3usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[4usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[5usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[6usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[7usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[8usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[9usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[10usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[11usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[12usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[13usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[14usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[15usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[16usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        tuple_elements[17usize]
                            .clone()
                            .into_address()
                            .expect(INTERNAL_ERR)
                            .as_bytes()
                            .to_vec(),
                        {
                            let mut result = [0u8; 32];
                            let v = tuple_elements[18usize]
                                .clone()
                                .into_fixed_bytes()
                                .expect(INTERNAL_ERR);
                            result.copy_from_slice(&v);
                            result
                        },
                        {
                            let mut result = [0u8; 32];
                            let v = tuple_elements[19usize]
                                .clone()
                                .into_fixed_bytes()
                                .expect(INTERNAL_ERR);
                            result.copy_from_slice(&v);
                            result
                        },
                    )
                },
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            ethabi::encode(
                &[
                    ethabi::Token::Tuple(
                        vec![
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.0)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.1)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.2)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.3)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.4)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.5)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.6)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.7)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.8)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.9)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.10)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.11)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.12)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.13)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.14)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.15)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.16)),
                            ethabi::Token::Address(ethabi::Address::from_slice(& self
                            .params.17)), ethabi::Token::FixedBytes(self.params.18
                            .as_ref().to_vec()), ethabi::Token::FixedBytes(self.params.19
                            .as_ref().to_vec())
                        ],
                    ),
                ],
            )
        }
    }
}
