// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {
    #[derive(Debug, Clone, PartialEq)]
    pub struct EnableFeatures {
        pub features: substreams::scalar::BigInt,
        pub enable: bool,
    }
    impl EnableFeatures {
        const METHOD_ID: [u8; 4] = [44u8, 112u8, 119u8, 192u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                features: substreams_ethereum::abi::read_uint(data, 0, "features")?,
                enable: substreams_ethereum::abi::read_bool(data, 32, "enable")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 64usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 64usize);
            substreams_ethereum::abi::write_uint_at(&mut out, base + 0, &self.features);
            substreams_ethereum::abi::write_bool_at(&mut out, base + 32, &self.enable);
            out
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
    }
    impl substreams_ethereum::Function for EnableFeatures {
        const NAME: &'static str = "enableFeatures";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct IsSupported {
        pub contract: Vec<u8>,
        pub features: substreams::scalar::BigInt,
    }
    impl IsSupported {
        const METHOD_ID: [u8; 4] = [165u8, 251u8, 242u8, 135u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            let maybe_data = call.input.get(4..);
            if maybe_data.is_none() {
                return Err("no data to decode".to_string());
            }
            let data = maybe_data.unwrap();
            Ok(Self {
                contract: substreams_ethereum::abi::read_address(data, 0, "contract")?,
                features: substreams_ethereum::abi::read_uint(data, 32, "features")?,
            })
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 64usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 64usize);
            substreams_ethereum::abi::write_address_at(
                &mut out,
                base + 0,
                &self.contract,
            );
            substreams_ethereum::abi::write_uint_at(&mut out, base + 32, &self.features);
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<bool, String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<bool, String> {
            Ok(substreams_ethereum::abi::read_bool(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<bool> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for IsSupported {
        const NAME: &'static str = "isSupported";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<bool> for IsSupported {
        fn output(data: &[u8]) -> Result<bool, String> {
            Self::output(data)
        }
    }
}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct FeaturesAddition {
        pub address: Vec<u8>,
        pub features: substreams::scalar::BigInt,
    }
    impl FeaturesAddition {
        const TOPIC_ID: [u8; 32] = [
            70u8,
            31u8,
            1u8,
            128u8,
            89u8,
            45u8,
            15u8,
            161u8,
            30u8,
            206u8,
            8u8,
            39u8,
            117u8,
            197u8,
            176u8,
            55u8,
            169u8,
            111u8,
            106u8,
            84u8,
            24u8,
            243u8,
            242u8,
            61u8,
            78u8,
            228u8,
            238u8,
            6u8,
            59u8,
            92u8,
            26u8,
            172u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 2usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 2usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 2usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                address: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "address",
                )?,
                features: substreams_ethereum::abi::read_uint(log.data(), 0, "features")?,
            })
        }
    }
    impl substreams_ethereum::Event for FeaturesAddition {
        const NAME: &'static str = "FeaturesAddition";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct FeaturesRemoval {
        pub address: Vec<u8>,
        pub features: substreams::scalar::BigInt,
    }
    impl FeaturesRemoval {
        const TOPIC_ID: [u8; 32] = [
            144u8,
            63u8,
            150u8,
            166u8,
            248u8,
            195u8,
            22u8,
            187u8,
            136u8,
            179u8,
            15u8,
            139u8,
            100u8,
            27u8,
            210u8,
            170u8,
            128u8,
            182u8,
            233u8,
            39u8,
            50u8,
            186u8,
            180u8,
            209u8,
            172u8,
            207u8,
            48u8,
            225u8,
            214u8,
            235u8,
            168u8,
            156u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 2usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 2usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 2usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                address: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "address",
                )?,
                features: substreams_ethereum::abi::read_uint(log.data(), 0, "features")?,
            })
        }
    }
    impl substreams_ethereum::Event for FeaturesRemoval {
        const NAME: &'static str = "FeaturesRemoval";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}

/// Contract's constructor arguments.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod constructor {
    const INTERNAL_ERR: &str = "`ethabi_derive` internal error";
    #[derive(Debug, Clone, PartialEq)]
    pub struct Constructor {}
    impl Constructor {
        pub fn decode(data: &[u8]) -> Result<Self, String> {
            Ok(Self {})
        }
        pub fn encode(&self) -> Vec<u8> {
            ethabi::encode(&[])
        }
    }
}
